export default {
    de: {
        days: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
        monday: "Montag",
        tuesday: "Dienstag",
        wednesday: "Mittwoch",
        thursday: "Donnerstag",
        friday: "Freitag",
        saturday: "Samstag",
        sunday: "Sonntag",

        navigation_home: "Profil",
        navigation_cookbook: "Kochbuch",
        navigation_informations: "Infos",
        navigation_medication: "Kalendar",
        navigation_settings: "Einstellungen",

        clock: "Uhr",

        recipe_favorites: "Deine Favoriten",
        breakfast: 'Frühstück',
        main_meal: 'Hauptspeiße',
        snack: 'Snack & Nachspeiße',
        shakes: 'Shakes',

        food: "Ernährung",
        sport_therapy: "Sport & Therapie",
        meditation: "Meditation",
        transplantation: "Transplantation",
        psychologie: "Psychologie",
        bueaucracy: "Bürokratie",

        add_medication: "Medikament hinzufügen",
        medication_schedule: "Meine\nMedikamente",
        medication_stock: "Mein\nVorrat",
        medication: "Medikamente",
        meals: "Mahlzeiten",
        vitaldata: "Vitaldaten",
        add_vitaldata: "Vitaldaten erfassen",
        add_doctor_report: "Arztbericht einscannen",
        to_reports: "Berichte",
        my_medical_progression: "Mein\nVerlauf",

        hello: "Hallo!",
        welcome_to_mucomed: "Herzlich Wilkommen bei MucoMed!",
        next: "Weiter",
        finished: "Fertig",
        news: "Neuigkeiten",
        search_for_something_to_eat: "Suchst du was zu essen?",
        reports_and_health: "Berichte & Gesundheit",

        pill: "Tablette",
        inhale: "Inhalieren",
        injection: "Spritze",
        other: "Anderes",

        introduction_about: "Über MucoMed",
        introduction_about_text: "MucoMed soll euch dabei helfen, euren Tag besser zu organisieren, euch an Medikationen erinnern und euren Gesundheitsverlauf selber nachvollziehen zu können. Das hier ist die Beta Version. Daher bin ich auf Hilfe und euer Feedback angewiesen! Ihr könnt mich also gerne kontaktieren 😊",
        introduction_privacy: "Datenschutz",
        introduction_privacy_text: "All eure Daten die ihr angebt gehören euch und werden ausschließlich auf eurem Smartphone gespeichert.",
        introduction_finish: "Fertig!",
        introduction_finish_text: "Viel Spaß mit MucoMed!",

        settings_general: "Allgemein",
        settings_creon_notification: "Kreoneinnahme am ende des Tages abfragen?",
        settings_notification: "Benachrichtigungen",
        settings_design: "Design",
        settings_color: "Farbschema",
        settings_color_light: "Helles Design",
        settings_color_dark: "Dunkles Design",
        settings_calendar_days: "Anzahl Tage im Kalendar",
        settings_language: "Sprache",
        settings_language_german: "Deutsch",
        settings_language_english: "English",
        settings_data: "Daten",
        settings_data_description: "Alle Daten werden für maximalem Datenschutz nur auf Ihrem Smartphone gespeichert.",
        settings_data_management: "Verwaltung",
        settings_data_export: "Daten exportieren",
        settings_data_import: "Daten importieren",
        settings_data_delete: "Daten löschen",
        settings_data_delete_description: "Achtung! Hierbei werden alle Daten (gespeicherte Mahlzeiten, Medikamente und Vitaldaten) gelöscht!",
        settings_data_collected_medication: "Erfasste Medikationen",
        settings_data_collected_vitaldata: "Erfasste Vitaldaten",
        settings_data_collected_meals: "Gespeicherte Mahlzeiten",
        settings_data_delete_all: "Alle Daten löschen",
        settings_data_delete_confirm: "Löschen bestätigen",

        info_hygiene: "Hygiene",
        info_food: "Ernährung",
        info_spores: "Keime",
        info_therapy: "Therapien",
        info_selfhelp: "Selbsthilfe",

        days_caption: "Tage",
    },
    en: {
        days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
        sunday: "Sunday",

        navigation_home: "Home",
        navigation_cookbook: "Cookery Book",
        navigation_informations: "Informations",
        navigation_medication: "Calendar",
        navigation_settings: "Settings",

        clock: "",

        recipe_favorites: "Your Favorites",
        breakfast: 'Breakfast',
        main_meal: 'Main meal',
        snack: 'Snacks',
        shakes: 'Shakes',

        food: "Nutrition",
        sport_therapy: "Sport & Therapy",
        meditation: "Meditation",
        transplantation: "Transplantation",
        psychologie: "Psychologie",
        bueaucracy: "Bureaucracy",

        add_medication: "Add Medication",
        medication_schedule: "My medications",
        medication_stock: "Medication stock",
        medication: "Medication",
        meals: "Meals",
        vitaldata: "Vitaldata",
        add_vitaldata: "Add vitaldata",
        add_doctor_report: "Scan doctor's report",
        to_reports: "Reports",
        my_medical_progression: "My progression",

        hello: "Hi!",
        welcome_to_mucomed: "Welcome to MucoMed!",
        next: "Next",
        finished: "Finished",
        news: "News",
        search_for_something_to_eat: "Looking for something to eat?",
        reports_and_health: "Reports & Health",

        pill: "pill",
        inhale: "inhale",
        injection: "injection",
        other: "other",

        introduction_about: "About MucoMed",
        introduction_about_text: "MucoMed is designed to help you better organize your day, remember medications, and track your health history yourself. This is the beta version. So I'm depending on your help and feedback! So feel free to contact me 😊",
        introduction_privacy: "Privacy",
        introduction_privacy_text: "All your data belongs to you. Everything you input is only saved on your phone.",
        introduction_finish: "Finished!",
        introduction_finish_text: "Much fun with MucoMed!",

        settings_general: "General",
        settings_creon_notification: "Check creon intake at the end of the day?",
        settings_notification: "Notifications",
        settings_design: "Design",
        settings_color: "Color scheme",
        settings_color_light: "Light colors",
        settings_color_dark: "Dark colors",
        settings_calendar_days: "Amount of calendar days",
        settings_language: "Language",
        settings_language_german: "Deutsch",
        settings_language_english: "English",
        settings_data: "Data",
        settings_data_description: "All data is stored only on your smartphone for maximum privacy.",
        settings_data_management: "Data management",
        settings_data_export: "Export data",
        settings_data_import: "Import data",
        settings_data_delete: "Delete data",
        settings_data_delete_description: "Warning! All data (stored meals, medications and vital data) will be deleted!",
        settings_data_collected_medication: "Recorded Medications",
        settings_data_collected_vitaldata: "Recorded Vitaldata",
        settings_data_collected_meals: "Recorded Meals",
        settings_data_delete_all: "Delete all data",
        settings_data_delete_confirm: "Confirm deletion",

        info_hygiene: "hygiene",
        info_food: "food",
        info_spores: "spores",
        info_therapy: "therapy",
        info_selfhelp: "Selfhelp",

        days_caption: "days",
    }
}